name: 'Docker Deployment'
description: 'Builds, pushes, and deploys a Docker image to a server'
inputs:
  registry:
    description: 'Docker registry URL'
    required: true
    default: 'ghcr.io'
  image_name:
    description: 'Docker image name'
    required: true
  service_name:
    description: 'Service name for deployment'
    required: true
  internal_port:
    description: 'Internal port of the service'
    required: true
  external_port:
    description: 'External port of the service'
    required: true
  server_user:
    description: 'Username for server access'
    required: true
  server_host:
    description: 'Server host for SSH'
    required: true
  server_ssh_private_key:
    description: 'SSH private key for server access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup SSH Key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.server_ssh_private_key }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ inputs.server_host }} >> ~/.ssh/known_hosts

    - name: Login to Docker Registry
      shell: bash
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ inputs.registry }} -u ${{ github.actor }} --password-stdin

    - name: Pull Docker Image
      shell: bash
      run: |
        docker pull ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.run_id }}

    - name: Remove old Docker service
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa ${{ inputs.server_user }}@${{ inputs.server_host }} \
        "docker service rm ${{ inputs.service_name }} || echo 'Service not found. Removing any old services.'"

    - name: Deploy Docker image as a service
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa ${{ inputs.server_user }}@${{ inputs.server_host }} \
        "docker service create --name ${{ inputs.service_name }} --publish published=${{ inputs.external_port }},target=${{ inputs.internal_port }} --replicas 1 ${{
        inputs.registry }}/${{ inputs.image_name }}:${{ github.run_id }}"
